export const useFetchAudio = [
  {
    id: 1,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Sơn Tùng MTP",
    },
    categories: "vietnamese",
    name: "Lạc Trôi",
    listener: 1000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    trend: false,
    popular: false,
    likeSong: false,
    thumbnail:
      "https://tse2.mm.bing.net/th/id/OIP.kUqOPj_lP3wSSlN5zut8ggHaHa?pid=Api&P=0&h=180",
  },
  {
    id: 2,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Sơn Tùng MTP",
    },
    categories: "vietnamese",
    name: "Em Đừng đi",
    listener: 5400,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    trend: false,
    popular: false,
    likeSong: true,
    thumbnail:
      "https://tse1.mm.bing.net/th/id/OIP.6PqMIQRYRDtYifLXSDzL6wHaEK?pid=Api&P=0&h=180",
  },
  {
    id: 3,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Sơn Tùng MTP",
    },
    categories: "vietnamese",
    name: "Anh Sai Rồi",
    listener: 22000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: false,
    popular: true,
    likeSong: false,
    thumbnail:
      "https://tse4.mm.bing.net/th/id/OIP.qCuLGiETXuMF_U3JJHRsOwHaEK?pid=Api&P=0&h=180",
  },
  {
    id: 4,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Black Pink",
    },
    categories: "korea",
    name: "Solo",
    listener: 30000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: false,
    popular: true,
    likeSong: true,
    thumbnail:
      "https://tse4.mm.bing.net/th/id/OIP.yo0HUrSgCFhR1S-UC7KxbwHaLH?pid=Api&P=0&h=180",
  },
  {
    id: 5,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Michita ft 愛海",
    },
    categories: "japan",
    name: "Cry For Me",
    listener: 30000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: true,
    popular: false,
    likeSong: false,
    thumbnail:
      "https://tse1.mm.bing.net/th/id/OIP.gw94KlAH6l4gOfReZTrawwHaEK?pid=Api&P=0&h=180",
  },
  {
    id: 6,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Mộng Nhiên",
    },
    categories: "chinese",
    name: "Thiếu Niên - 少年",
    listener: 30000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: true,
    popular: false,
    likeSong: true,
    thumbnail:
      "https://tse2.mm.bing.net/th/id/OIP.e8WPtVl6PihypO3lAPa-FgHaEK?pid=Api&P=0&h=180",
  },
  {
    id: 7,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Sơn Tùng MTP",
    },
    categories: "vietnamese",
    name: "Nơi Này Có Anh",
    listener: 30000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: false,
    popular: false,
    likeSong: false,
    thumbnail:
      "https://tse3.mm.bing.net/th/id/OIP.-MuzX5PeO4S8NLIrZ2_YMAHaHa?pid=Api&P=0&h=180",
  },
  {
    id: 8,
    userId: 1,
    user: {
      fullName: "Cybersoft",
      artist: "Sơn Tùng MTP",
    },
    categories: "vietnamese",
    name: "Chắc Ai Đó Sẽ Về",
    listener: 80000,
    music: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    trend: false,
    popular: false,
    likeSong: false,
    thumbnail:
      "https://tse2.mm.bing.net/th/id/OIP.M34EejozeZzOGUzOyPxutgHaHa?pid=Api&P=0&h=180",
  },
];
